baseURL = "https://www.moonstone-ink.nl/"
languageCode = "en-us"
title = "Moonstone Ink"
theme = "creative-portfolio"
googleAnalytics = "UA-214949813-1"

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "sea"
  description = "Moonstone Ink tattoo art"
  copyright = "&copy;2022 Moonstone Ink"
  sidebarAbout = [
    "</p><a href='/portfolio/'><img src='/img/logo/moonstone_logo.png' width='80%' height='80%'></a><p class=sidebar-p>",
    "My name is Emmely. I live in Groningen. I started tattooing in 2020. Iâ€™ve been drawing since I was able to hold a pencil ğŸ˜Œ Learning how to tattoo felt like drawing with a new tool on skin instead of paper ğŸŒ",
    "Last year I realized my ultimate dream; opening my own tattoo shop. Iâ€™m the proud owner of Tattoo studio Moonstone Ink ğŸŒ™  Itâ€™s located in Groningen at the Travertijnstraat 6.",
    "I came up with the name Moonstone Ink for my business for a reason. I wear moonstones in most of my jewelry and felt a connection with them for a while ğŸ’",
    "For my logo used a picture of my own hand holding my tattoo machine. Moonstones are connected to feminine energy, stands for self awareness, stimulates creativity and helps you through personal changes âœ¨",
    "It felt like a perfect match for this new journey in my life. I also give my customers a moonstone as a little gift after their tattoo session ğŸŒ™",
    "This page contains a small set of my portfolio, for more work please see my <a href='https://www.instagram.com/moonstone.ink.tattoos'>instagram</a>.",
    "If you would like to book an appointment, please send me a DM on instagram or contact me through email (see the icons below)."
  ]
  email = "info@moonstone-ink.nl"

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = "portfolio/"
  home = true

  [[params.navlinks]]
  name = "Available Designs"
  url = "art/"

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [params.social]
  facebook      = "https://www.facebook.com/Moonstone-Ink-104925165106680/"
  email         = "info@moonstone-ink.nl"
  instagram     = "https://www.instagram.com/moonstone.ink.tattoos"
